default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['MEGATOURNAMENT_DATABASE_USERNAME'] %>
  password: <%= ENV['MEGATOURNAMENT_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: megatournament_development
  host: localhost

test:
  <<: *default
  database: megatournament_test
  host: localhost
